// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: storage.proto
#ifndef GRPC_storage_2eproto__INCLUDED
#define GRPC_storage_2eproto__INCLUDED

#include "storage.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace storage {

// ============================================================
// Storage Service
// ============================================================
//
class StorageService final {
 public:
  static constexpr char const* service_full_name() {
    return "storage.StorageService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::storage::UploadResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::UploadResponse>> AsyncUploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::UploadResponse>>(AsyncUploadFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::UploadResponse>> PrepareAsyncUploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::UploadResponse>>(PrepareAsyncUploadFileRaw(context, request, cq));
    }
    virtual ::grpc::Status DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::storage::DownloadResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::DownloadResponse>> AsyncDownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::DownloadResponse>>(AsyncDownloadFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::DownloadResponse>> PrepareAsyncDownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::DownloadResponse>>(PrepareAsyncDownloadFileRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::UploadResponse>* AsyncUploadFileRaw(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::UploadResponse>* PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::DownloadResponse>* AsyncDownloadFileRaw(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::DownloadResponse>* PrepareAsyncDownloadFileRaw(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::storage::UploadResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::UploadResponse>> AsyncUploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::UploadResponse>>(AsyncUploadFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::UploadResponse>> PrepareAsyncUploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::UploadResponse>>(PrepareAsyncUploadFileRaw(context, request, cq));
    }
    ::grpc::Status DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::storage::DownloadResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::DownloadResponse>> AsyncDownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::DownloadResponse>>(AsyncDownloadFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::DownloadResponse>> PrepareAsyncDownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::DownloadResponse>>(PrepareAsyncDownloadFileRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response, std::function<void(::grpc::Status)>) override;
      void UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response, std::function<void(::grpc::Status)>) override;
      void DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::storage::UploadResponse>* AsyncUploadFileRaw(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storage::UploadResponse>* PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storage::DownloadResponse>* AsyncDownloadFileRaw(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storage::DownloadResponse>* PrepareAsyncDownloadFileRaw(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UploadFile_;
    const ::grpc::internal::RpcMethod rpcmethod_DownloadFile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status UploadFile(::grpc::ServerContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response);
    virtual ::grpc::Status DownloadFile(::grpc::ServerContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UploadFile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, const ::storage::UploadRequest* /*request*/, ::storage::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadFile(::grpc::ServerContext* context, ::storage::UploadRequest* request, ::grpc::ServerAsyncResponseWriter< ::storage::UploadResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DownloadFile() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::storage::DownloadRequest* /*request*/, ::storage::DownloadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDownloadFile(::grpc::ServerContext* context, ::storage::DownloadRequest* request, ::grpc::ServerAsyncResponseWriter< ::storage::DownloadResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UploadFile<WithAsyncMethod_DownloadFile<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UploadFile() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::storage::UploadRequest, ::storage::UploadResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response) { return this->UploadFile(context, request, response); }));}
    void SetMessageAllocatorFor_UploadFile(
        ::grpc::MessageAllocator< ::storage::UploadRequest, ::storage::UploadResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storage::UploadRequest, ::storage::UploadResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, const ::storage::UploadRequest* /*request*/, ::storage::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UploadFile(
      ::grpc::CallbackServerContext* /*context*/, const ::storage::UploadRequest* /*request*/, ::storage::UploadResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DownloadFile() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::storage::DownloadRequest, ::storage::DownloadResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response) { return this->DownloadFile(context, request, response); }));}
    void SetMessageAllocatorFor_DownloadFile(
        ::grpc::MessageAllocator< ::storage::DownloadRequest, ::storage::DownloadResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storage::DownloadRequest, ::storage::DownloadResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::storage::DownloadRequest* /*request*/, ::storage::DownloadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DownloadFile(
      ::grpc::CallbackServerContext* /*context*/, const ::storage::DownloadRequest* /*request*/, ::storage::DownloadResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UploadFile<WithCallbackMethod_DownloadFile<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UploadFile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, const ::storage::UploadRequest* /*request*/, ::storage::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DownloadFile() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::storage::DownloadRequest* /*request*/, ::storage::DownloadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UploadFile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, const ::storage::UploadRequest* /*request*/, ::storage::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DownloadFile() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::storage::DownloadRequest* /*request*/, ::storage::DownloadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDownloadFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UploadFile() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UploadFile(context, request, response); }));
    }
    ~WithRawCallbackMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, const ::storage::UploadRequest* /*request*/, ::storage::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UploadFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DownloadFile() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DownloadFile(context, request, response); }));
    }
    ~WithRawCallbackMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::storage::DownloadRequest* /*request*/, ::storage::DownloadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DownloadFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UploadFile() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storage::UploadRequest, ::storage::UploadResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storage::UploadRequest, ::storage::UploadResponse>* streamer) {
                       return this->StreamedUploadFile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, const ::storage::UploadRequest* /*request*/, ::storage::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUploadFile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storage::UploadRequest,::storage::UploadResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DownloadFile() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storage::DownloadRequest, ::storage::DownloadResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storage::DownloadRequest, ::storage::DownloadResponse>* streamer) {
                       return this->StreamedDownloadFile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::storage::DownloadRequest* /*request*/, ::storage::DownloadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDownloadFile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storage::DownloadRequest,::storage::DownloadResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UploadFile<WithStreamedUnaryMethod_DownloadFile<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UploadFile<WithStreamedUnaryMethod_DownloadFile<Service > > StreamedService;
};

// ============================================================
// Master Service
// ============================================================
//
class MasterService final {
 public:
  static constexpr char const* service_full_name() {
    return "storage.MasterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::storage::RegisterNodeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::RegisterNodeResponse>> AsyncRegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::RegisterNodeResponse>>(AsyncRegisterNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::RegisterNodeResponse>> PrepareAsyncRegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::RegisterNodeResponse>>(PrepareAsyncRegisterNodeRaw(context, request, cq));
    }
    virtual ::grpc::Status CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::storage::NodeHealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::NodeHealthResponse>> AsyncCheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::NodeHealthResponse>>(AsyncCheckNodeHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::NodeHealthResponse>> PrepareAsyncCheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::NodeHealthResponse>>(PrepareAsyncCheckNodeHealthRaw(context, request, cq));
    }
    virtual ::grpc::Status GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::storage::GetNodesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::GetNodesResponse>> AsyncGetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::GetNodesResponse>>(AsyncGetNodesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::GetNodesResponse>> PrepareAsyncGetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storage::GetNodesResponse>>(PrepareAsyncGetNodesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::RegisterNodeResponse>* AsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::RegisterNodeResponse>* PrepareAsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::NodeHealthResponse>* AsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::NodeHealthResponse>* PrepareAsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::GetNodesResponse>* AsyncGetNodesRaw(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storage::GetNodesResponse>* PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::storage::RegisterNodeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::RegisterNodeResponse>> AsyncRegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::RegisterNodeResponse>>(AsyncRegisterNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::RegisterNodeResponse>> PrepareAsyncRegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::RegisterNodeResponse>>(PrepareAsyncRegisterNodeRaw(context, request, cq));
    }
    ::grpc::Status CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::storage::NodeHealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::NodeHealthResponse>> AsyncCheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::NodeHealthResponse>>(AsyncCheckNodeHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::NodeHealthResponse>> PrepareAsyncCheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::NodeHealthResponse>>(PrepareAsyncCheckNodeHealthRaw(context, request, cq));
    }
    ::grpc::Status GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::storage::GetNodesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::GetNodesResponse>> AsyncGetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::GetNodesResponse>>(AsyncGetNodesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::GetNodesResponse>> PrepareAsyncGetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storage::GetNodesResponse>>(PrepareAsyncGetNodesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response, std::function<void(::grpc::Status)>) override;
      void RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response, std::function<void(::grpc::Status)>) override;
      void CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response, std::function<void(::grpc::Status)>) override;
      void GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::storage::RegisterNodeResponse>* AsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storage::RegisterNodeResponse>* PrepareAsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storage::NodeHealthResponse>* AsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storage::NodeHealthResponse>* PrepareAsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storage::GetNodesResponse>* AsyncGetNodesRaw(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storage::GetNodesResponse>* PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterNode_;
    const ::grpc::internal::RpcMethod rpcmethod_CheckNodeHealth_;
    const ::grpc::internal::RpcMethod rpcmethod_GetNodes_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterNode(::grpc::ServerContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response);
    virtual ::grpc::Status CheckNodeHealth(::grpc::ServerContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response);
    virtual ::grpc::Status GetNodes(::grpc::ServerContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterNode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::storage::RegisterNodeRequest* /*request*/, ::storage::RegisterNodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterNode(::grpc::ServerContext* context, ::storage::RegisterNodeRequest* request, ::grpc::ServerAsyncResponseWriter< ::storage::RegisterNodeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::storage::NodeHealthRequest* /*request*/, ::storage::NodeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckNodeHealth(::grpc::ServerContext* context, ::storage::NodeHealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::storage::NodeHealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetNodes() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::storage::GetNodesRequest* /*request*/, ::storage::GetNodesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNodes(::grpc::ServerContext* context, ::storage::GetNodesRequest* request, ::grpc::ServerAsyncResponseWriter< ::storage::GetNodesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterNode<WithAsyncMethod_CheckNodeHealth<WithAsyncMethod_GetNodes<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterNode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::storage::RegisterNodeRequest, ::storage::RegisterNodeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response) { return this->RegisterNode(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterNode(
        ::grpc::MessageAllocator< ::storage::RegisterNodeRequest, ::storage::RegisterNodeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storage::RegisterNodeRequest, ::storage::RegisterNodeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::storage::RegisterNodeRequest* /*request*/, ::storage::RegisterNodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterNode(
      ::grpc::CallbackServerContext* /*context*/, const ::storage::RegisterNodeRequest* /*request*/, ::storage::RegisterNodeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::storage::NodeHealthRequest, ::storage::NodeHealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response) { return this->CheckNodeHealth(context, request, response); }));}
    void SetMessageAllocatorFor_CheckNodeHealth(
        ::grpc::MessageAllocator< ::storage::NodeHealthRequest, ::storage::NodeHealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storage::NodeHealthRequest, ::storage::NodeHealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::storage::NodeHealthRequest* /*request*/, ::storage::NodeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckNodeHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::storage::NodeHealthRequest* /*request*/, ::storage::NodeHealthResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetNodes() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::storage::GetNodesRequest, ::storage::GetNodesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response) { return this->GetNodes(context, request, response); }));}
    void SetMessageAllocatorFor_GetNodes(
        ::grpc::MessageAllocator< ::storage::GetNodesRequest, ::storage::GetNodesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storage::GetNodesRequest, ::storage::GetNodesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::storage::GetNodesRequest* /*request*/, ::storage::GetNodesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNodes(
      ::grpc::CallbackServerContext* /*context*/, const ::storage::GetNodesRequest* /*request*/, ::storage::GetNodesResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterNode<WithCallbackMethod_CheckNodeHealth<WithCallbackMethod_GetNodes<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterNode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::storage::RegisterNodeRequest* /*request*/, ::storage::RegisterNodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::storage::NodeHealthRequest* /*request*/, ::storage::NodeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetNodes() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::storage::GetNodesRequest* /*request*/, ::storage::GetNodesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterNode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::storage::RegisterNodeRequest* /*request*/, ::storage::RegisterNodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterNode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::storage::NodeHealthRequest* /*request*/, ::storage::NodeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckNodeHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetNodes() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::storage::GetNodesRequest* /*request*/, ::storage::GetNodesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNodes(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterNode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterNode(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::storage::RegisterNodeRequest* /*request*/, ::storage::RegisterNodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterNode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckNodeHealth(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::storage::NodeHealthRequest* /*request*/, ::storage::NodeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckNodeHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetNodes() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetNodes(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::storage::GetNodesRequest* /*request*/, ::storage::GetNodesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNodes(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterNode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storage::RegisterNodeRequest, ::storage::RegisterNodeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storage::RegisterNodeRequest, ::storage::RegisterNodeResponse>* streamer) {
                       return this->StreamedRegisterNode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterNode(::grpc::ServerContext* /*context*/, const ::storage::RegisterNodeRequest* /*request*/, ::storage::RegisterNodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterNode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storage::RegisterNodeRequest,::storage::RegisterNodeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storage::NodeHealthRequest, ::storage::NodeHealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storage::NodeHealthRequest, ::storage::NodeHealthResponse>* streamer) {
                       return this->StreamedCheckNodeHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::storage::NodeHealthRequest* /*request*/, ::storage::NodeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckNodeHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storage::NodeHealthRequest,::storage::NodeHealthResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetNodes() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storage::GetNodesRequest, ::storage::GetNodesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storage::GetNodesRequest, ::storage::GetNodesResponse>* streamer) {
                       return this->StreamedGetNodes(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::storage::GetNodesRequest* /*request*/, ::storage::GetNodesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNodes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storage::GetNodesRequest,::storage::GetNodesResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterNode<WithStreamedUnaryMethod_CheckNodeHealth<WithStreamedUnaryMethod_GetNodes<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterNode<WithStreamedUnaryMethod_CheckNodeHealth<WithStreamedUnaryMethod_GetNodes<Service > > > StreamedService;
};

}  // namespace storage


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_storage_2eproto__INCLUDED
