// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: storage.proto

#include "storage.pb.h"
#include "storage.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace storage {

static const char* StorageService_method_names[] = {
  "/storage.StorageService/UploadFile",
  "/storage.StorageService/DownloadFile",
};

std::unique_ptr< StorageService::Stub> StorageService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StorageService::Stub> stub(new StorageService::Stub(channel, options));
  return stub;
}

StorageService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_UploadFile_(StorageService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DownloadFile_(StorageService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StorageService::Stub::UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::storage::UploadResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::UploadRequest, ::storage::UploadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UploadFile_, context, request, response);
}

void StorageService::Stub::async::UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::UploadRequest, ::storage::UploadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, request, response, std::move(f));
}

void StorageService::Stub::async::UploadFile(::grpc::ClientContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::UploadResponse>* StorageService::Stub::PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::UploadResponse, ::storage::UploadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UploadFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::UploadResponse>* StorageService::Stub::AsyncUploadFileRaw(::grpc::ClientContext* context, const ::storage::UploadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUploadFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StorageService::Stub::DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::storage::DownloadResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::DownloadRequest, ::storage::DownloadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DownloadFile_, context, request, response);
}

void StorageService::Stub::async::DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::DownloadRequest, ::storage::DownloadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DownloadFile_, context, request, response, std::move(f));
}

void StorageService::Stub::async::DownloadFile(::grpc::ClientContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DownloadFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::DownloadResponse>* StorageService::Stub::PrepareAsyncDownloadFileRaw(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::DownloadResponse, ::storage::DownloadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DownloadFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::DownloadResponse>* StorageService::Stub::AsyncDownloadFileRaw(::grpc::ClientContext* context, const ::storage::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDownloadFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

StorageService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::storage::UploadRequest, ::storage::UploadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StorageService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::UploadRequest* req,
             ::storage::UploadResponse* resp) {
               return service->UploadFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::storage::DownloadRequest, ::storage::DownloadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StorageService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::DownloadRequest* req,
             ::storage::DownloadResponse* resp) {
               return service->DownloadFile(ctx, req, resp);
             }, this)));
}

StorageService::Service::~Service() {
}

::grpc::Status StorageService::Service::UploadFile(::grpc::ServerContext* context, const ::storage::UploadRequest* request, ::storage::UploadResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::DownloadFile(::grpc::ServerContext* context, const ::storage::DownloadRequest* request, ::storage::DownloadResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* MasterService_method_names[] = {
  "/storage.MasterService/RegisterNode",
  "/storage.MasterService/CheckNodeHealth",
  "/storage.MasterService/GetNodes",
};

std::unique_ptr< MasterService::Stub> MasterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MasterService::Stub> stub(new MasterService::Stub(channel, options));
  return stub;
}

MasterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterNode_(MasterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CheckNodeHealth_(MasterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodes_(MasterService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MasterService::Stub::RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::storage::RegisterNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::RegisterNodeRequest, ::storage::RegisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterNode_, context, request, response);
}

void MasterService::Stub::async::RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::RegisterNodeRequest, ::storage::RegisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterNode_, context, request, response, std::move(f));
}

void MasterService::Stub::async::RegisterNode(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::RegisterNodeResponse>* MasterService::Stub::PrepareAsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::RegisterNodeResponse, ::storage::RegisterNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::RegisterNodeResponse>* MasterService::Stub::AsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::storage::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::storage::NodeHealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::NodeHealthRequest, ::storage::NodeHealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckNodeHealth_, context, request, response);
}

void MasterService::Stub::async::CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::NodeHealthRequest, ::storage::NodeHealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckNodeHealth_, context, request, response, std::move(f));
}

void MasterService::Stub::async::CheckNodeHealth(::grpc::ClientContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckNodeHealth_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::NodeHealthResponse>* MasterService::Stub::PrepareAsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::NodeHealthResponse, ::storage::NodeHealthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckNodeHealth_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::NodeHealthResponse>* MasterService::Stub::AsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::storage::NodeHealthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckNodeHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MasterService::Stub::GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::storage::GetNodesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::GetNodesRequest, ::storage::GetNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNodes_, context, request, response);
}

void MasterService::Stub::async::GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::GetNodesRequest, ::storage::GetNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodes_, context, request, response, std::move(f));
}

void MasterService::Stub::async::GetNodes(::grpc::ClientContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::GetNodesResponse>* MasterService::Stub::PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::GetNodesResponse, ::storage::GetNodesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNodes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::GetNodesResponse>* MasterService::Stub::AsyncGetNodesRaw(::grpc::ClientContext* context, const ::storage::GetNodesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodesRaw(context, request, cq);
  result->StartCall();
  return result;
}

MasterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::storage::RegisterNodeRequest, ::storage::RegisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::RegisterNodeRequest* req,
             ::storage::RegisterNodeResponse* resp) {
               return service->RegisterNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::storage::NodeHealthRequest, ::storage::NodeHealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::NodeHealthRequest* req,
             ::storage::NodeHealthResponse* resp) {
               return service->CheckNodeHealth(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MasterService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MasterService::Service, ::storage::GetNodesRequest, ::storage::GetNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::GetNodesRequest* req,
             ::storage::GetNodesResponse* resp) {
               return service->GetNodes(ctx, req, resp);
             }, this)));
}

MasterService::Service::~Service() {
}

::grpc::Status MasterService::Service::RegisterNode(::grpc::ServerContext* context, const ::storage::RegisterNodeRequest* request, ::storage::RegisterNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::CheckNodeHealth(::grpc::ServerContext* context, const ::storage::NodeHealthRequest* request, ::storage::NodeHealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MasterService::Service::GetNodes(::grpc::ServerContext* context, const ::storage::GetNodesRequest* request, ::storage::GetNodesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace storage
#include <grpcpp/ports_undef.inc>

